site_name: Book of RC
site_url: https://matt-the-ogre.github.io/book-of-rc
site_author: Matt Manuel
site_description: A book to help people discover and thrive in the world of Remote Control (RC) vehicles.

theme:
  name: material
  logo: images/logo.webp

extra:
  head:
    - '<link rel="icon" type="image/png" href="images/favicons/favicon-32x32.png" sizes="32x32">'
    - '<link rel="icon" type="image/png" href="images/favicons/favicon-16x16.png" sizes="16x16">'
    - '<link rel="icon" type="image/png" href="images/favicons/favicon-48x48.png" sizes="48x48">'
    - '<link rel="apple-touch-icon" href="images/favicons/favicon-180x180.png">'
    - '<link rel="icon" type="image/x-icon" href="images/favicons/favicon.ico">'

nav:
  - Home: index.md
  - The Basics of RC Vehicle Components:
      - Introduction: basics/index.md
      - Motors: basics/motors.md
      - Batteries: basics/batteries.md
      - ESCs: basics/escs.md
      - Tires: basics/tires-and-wheels.md
      - Controllers (Transmitter/Receiver): basics/controllers.md
      - Servos: basics/servos.md
      - Connectors: basics/connectors.md
      - Putting it All Together: basics/putting-it-all-together.md
